### model
model_name_or_path: /inspire/ssd/project/sais-bio/public/tupeng/LLaMA-Factory/huggingface/weights/LLM-Research/Meta-Llama-3-8B-Instruct
quantization_bit: 4  # choices: [8 (bnb/hqq/eetq), 4 (bnb/hqq), 3 (hqq), 2 (hqq)]
quantization_method: bnb  # choices: [bnb, hqq, eetq]
trust_remote_code: true

### method
stage: sft
do_train: true
finetuning_type: lora
lora_rank: 8
lora_target: all
use_unsloth: true

### dataset
dataset: alpaca_100proteins
template: llama3
cutoff_len: 9000
max_samples: 100000000000
overwrite_cache: true
preprocessing_num_workers: 16
dataloader_num_workers: 4
tokenized_path: saves/llama3-8b/dataset/sft

### output
output_dir: saves/llama3-8b/qlora/sft
logging_steps: 10
save_steps: 500
plot_loss: true
overwrite_output_dir: true
save_only_model: false
report_to: none  # choices: [none, wandb, tensorboard, swanlab, mlflow]

### train
per_device_train_batch_size: 4
gradient_accumulation_steps: 1
learning_rate: 1.0e-4
num_train_epochs: 10.0
lr_scheduler_type: cosine
warmup_ratio: 0.1
bf16: true
ddp_timeout: 180000000

### eval
# val_size: 0.1
# per_device_eval_batch_size: 1
# eval_strategy: steps
# eval_steps: 500
